/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

/**
 *
 * @author docto
 */
public class CalculatorClient extends javax.swing.JFrame {
    private static final String url = "http://localhost:8080/calc/cal";
    /**
     * Creates new form CalculatorClient
     */
    public CalculatorClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        calc_screen = new javax.swing.JTextField();
        seven_button = new javax.swing.JButton();
        eight_button = new javax.swing.JButton();
        nine_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        four_button = new javax.swing.JButton();
        five_button = new javax.swing.JButton();
        six_button = new javax.swing.JButton();
        sub_button = new javax.swing.JButton();
        one_button = new javax.swing.JButton();
        two_button = new javax.swing.JButton();
        three_button = new javax.swing.JButton();
        mult_button = new javax.swing.JButton();
        zero_button = new javax.swing.JButton();
        equals_button = new javax.swing.JButton();
        div_button = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calc_screen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        seven_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seven_button.setText("7");
        seven_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_buttonActionPerformed(evt);
            }
        });

        eight_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eight_button.setText("8");
        eight_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eight_buttonActionPerformed(evt);
            }
        });

        nine_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nine_button.setText("9");
        nine_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine_buttonActionPerformed(evt);
            }
        });

        add_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_button.setText("+");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        four_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        four_button.setText("4");
        four_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_buttonActionPerformed(evt);
            }
        });

        five_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        five_button.setText("5");
        five_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_buttonActionPerformed(evt);
            }
        });

        six_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        six_button.setText("6");
        six_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_buttonActionPerformed(evt);
            }
        });

        sub_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub_button.setText("-");
        sub_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_buttonActionPerformed(evt);
            }
        });

        one_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        one_button.setText("1");
        one_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_buttonActionPerformed(evt);
            }
        });

        two_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        two_button.setText("2");
        two_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_buttonActionPerformed(evt);
            }
        });

        three_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        three_button.setText("3");
        three_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_buttonActionPerformed(evt);
            }
        });

        mult_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mult_button.setText("*");
        mult_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mult_buttonActionPerformed(evt);
            }
        });

        zero_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zero_button.setText("0");
        zero_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_buttonActionPerformed(evt);
            }
        });

        equals_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        equals_button.setText("=");
        equals_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equals_buttonActionPerformed(evt);
            }
        });

        div_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        div_button.setText("/");
        div_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                div_buttonActionPerformed(evt);
            }
        });

        clear_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clear_button.setText("clear");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        back_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back_button.setText("←");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calc_screen)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(one_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(two_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(three_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mult_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seven_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eight_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nine_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(four_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(five_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(six_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sub_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(zero_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equals_button, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(div_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calc_screen, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seven_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(four_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(one_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mult_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zero_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equals_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(div_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mult_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mult_buttonActionPerformed
        String contents = calc_screen.getText();
        if(contents.contains("=")){
            int index = contents.indexOf("=") - 1;
            contents = contents.substring(0, index);
        }
        if(contents.contains("/")){
            System.out.println("hi");
            contents = contents.replace("/", "*");
        }
        else if(contents.contains("+"))
            contents = contents.replace("+", "*");
        else if(contents.contains("-"))
            contents = contents.replace("-", "*");
        else if(contents.contains("*"))
            ;
        else {
            if(!contents.equals(""))
                contents = contents + " * ";
        }
        calc_screen.setText(contents);
    }//GEN-LAST:event_mult_buttonActionPerformed

    private void five_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_buttonActionPerformed
        // TODO add your handling code here:
        String contents = calc_screen.getText();
        int index;
        if(contents.contains("=")){
            index = contents.indexOf("=")-1;
            contents = contents.substring(0, index);
        }
        calc_screen.setText(contents + "5");
    }//GEN-LAST:event_five_buttonActionPerformed

    private void zero_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_buttonActionPerformed
        // TODO add your handling code here:
        String contents = calc_screen.getText();
        int index;
        if(contents.contains("=")){
            index = contents.indexOf("=")-1;
            contents = contents.substring(0, index);
        }
        calc_screen.setText(contents + "0");
    }//GEN-LAST:event_zero_buttonActionPerformed

    private void equals_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equals_buttonActionPerformed
        // TODO add your handling code here:
        String contents = calc_screen.getText();
        String[ ] parts = contents.split(" ");
        if(parts.length == 3)
            sendRequest(parts[0], parts[1], parts[2]);
    }//GEN-LAST:event_equals_buttonActionPerformed

    private void div_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_div_buttonActionPerformed
        // TODO add your handling code here:
        String contents = calc_screen.getText();
        if(contents.contains("=")){
            int index = contents.indexOf("=") - 1;
            contents = contents.substring(0, index);
        }
        if(contents.contains("-"))
            contents = contents.replace("-", "/");
        else if(contents.contains("+"))
            contents = contents.replace("+", "/");
        else if(contents.contains("*"))
            contents = contents.replace("*", "/");
        else if(contents.contains("/"))
            ;
        else {
            if(!contents.equals(""))
                contents = contents + " / ";
        }
        calc_screen.setText(contents);
    }//GEN-LAST:event_div_buttonActionPerformed

    private void one_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_buttonActionPerformed
        // TODO add your handling code here:
        String contents = calc_screen.getText();
        int index;
        if(contents.contains("=")){
            index = contents.indexOf("=")-1;
            contents = contents.substring(0, index);
        }
        calc_screen.setText(contents + "1");
    }//GEN-LAST:event_one_buttonActionPerformed

    private void two_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_buttonActionPerformed
        String contents = calc_screen.getText();
        int index;
        if(contents.contains("=")){
            index = contents.indexOf("=")-1;
            contents = contents.substring(0, index);
        }
        calc_screen.setText(contents + "2");
    }//GEN-LAST:event_two_buttonActionPerformed

    private void three_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_buttonActionPerformed
        String contents = calc_screen.getText();
        int index;
        if(contents.contains("=")){
            index = contents.indexOf("=")-1;
            contents = contents.substring(0, index);
        }
        calc_screen.setText(contents + "3");
    }//GEN-LAST:event_three_buttonActionPerformed

    private void four_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_buttonActionPerformed
        String contents = calc_screen.getText();
        int index;
        if(contents.contains("=")){
            index = contents.indexOf("=")-1;
            contents = contents.substring(0, index);
        }
        calc_screen.setText(contents + "4");
    }//GEN-LAST:event_four_buttonActionPerformed

    private void six_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_buttonActionPerformed
        String contents = calc_screen.getText();
        int index;
        if(contents.contains("=")){
            index = contents.indexOf("=")-1;
            contents = contents.substring(0, index);
        }
        calc_screen.setText(contents + "6");
    }//GEN-LAST:event_six_buttonActionPerformed

    private void sub_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_buttonActionPerformed
        // TODO add your handling code here:
        String contents = calc_screen.getText();
        if(contents.contains("=")){
            int index = contents.indexOf("=") - 1;
            contents = contents.substring(0, index);
        }
        if(contents.contains("/"))
            contents = contents.replace("/", "-");
        else if(contents.contains("+"))
            contents = contents.replace("+", "-");
        else if(contents.contains("*"))
            contents = contents.replace("*", "-");
        else if(contents.contains("-"))
            ;
        else {
            if(!contents.equals(""))
                contents = contents + " - ";
        }
        calc_screen.setText(contents);
    }//GEN-LAST:event_sub_buttonActionPerformed

    private void seven_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_buttonActionPerformed
        String contents = calc_screen.getText();
        int index;
        if(contents.contains("=")){
            index = contents.indexOf("=")-1;
            contents = contents.substring(0, index);
        }
        calc_screen.setText(contents + "7");
    }//GEN-LAST:event_seven_buttonActionPerformed

    private void eight_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eight_buttonActionPerformed
        String contents = calc_screen.getText();
        int index;
        if(contents.contains("=")){
            index = contents.indexOf("=")-1;
            contents = contents.substring(0, index);
        }
        calc_screen.setText(contents + "8");
    }//GEN-LAST:event_eight_buttonActionPerformed

    private void nine_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine_buttonActionPerformed
        String contents = calc_screen.getText();
        int index;
        if(contents.contains("=")){
            index = contents.indexOf("=")-1;
            contents = contents.substring(0, index);
        }
        calc_screen.setText(contents + "9");
    }//GEN-LAST:event_nine_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
        String contents = calc_screen.getText();
        if(contents.contains("=")){
            int index = contents.indexOf("=") - 1;
            contents = contents.substring(0, index);
        }
        if(contents.contains("-"))
            contents = contents.replace("-", "+");
        else if(contents.contains("/"))
            contents = contents.replace("/", "+");
        else if(contents.contains("*"))
            contents = contents.replace("*", "+");
        else if(contents.contains("+"))
            ;
        else{
            if(!contents.equals(""))
                contents = contents + " + ";
        }
        calc_screen.setText(contents);
    }//GEN-LAST:event_add_buttonActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
        calc_screen.setText("");
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        String contents = calc_screen.getText();
        if(contents.contains("=")){
            int index = contents.indexOf("=") - 1;
            contents = contents.substring(0, index);
        }
        else{
            if(!contents.equals("")){
                int endChar = contents.length();
                String lastChar = contents.substring(endChar-1, endChar);
                if(lastChar.equals(" ")){
                    contents = contents.substring(0, contents.length() - 1);
                }
                contents = contents.substring(0, contents.length() - 1);
                if(!contents.equals("")){
                    endChar = contents.length();
                    lastChar = contents.substring(endChar-1, endChar);
                    if(lastChar.equals(" ")){
                        contents = contents.substring(0, endChar - 1);
                    }  
                }
            }
        }
        calc_screen.setText(contents);
    }//GEN-LAST:event_back_buttonActionPerformed

    
    private void sendRequest(String val1, String op, String val2){
        try {
            if(op.equals("+")){
                op = "1";
            }
            else if(op.equals("-")){
                op = "2";
            }
            else if(op.equals("*")){
                op = "3";
            }
            else if(op.equals("/")){
                op = "4";
            }
            HttpURLConnection conn = null;
            String requestURL = url + "?val1=" + val1 + "&op=" + op + "&val2=" + val2;
            System.out.println(requestURL);
            conn = get_connection(requestURL, "GET");
            conn.addRequestProperty("accept", "text/plain");
            conn.connect();
            get_response(conn);
        }
        catch(IOException e) { System.err.println(e); }
        catch(NullPointerException e) { System.err.println(e); }
    }
    
    
    private HttpURLConnection get_connection(String url_string, String verb) {
        HttpURLConnection conn = null;
        try {
            URL url = new URL(url_string);
            conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod(verb);
            conn.setDoInput(true);
            conn.setDoOutput(true);
        }
        catch(MalformedURLException e) { System.err.println(e); }
        catch(IOException e) { System.err.println(e); }
        return conn;
    }
    
    private void get_response(HttpURLConnection conn) {
        try {
            String xml = "";
            BufferedReader reader =
                new BufferedReader(new InputStreamReader(conn.getInputStream()));
            String next = null;
            while ((next = reader.readLine()) != null)
                xml += next;
            String contents = calc_screen.getText();
            if(contents.contains("=")){
                int index = contents.indexOf("=") - 1;
                contents = contents.substring(0, index);
            }
            contents = contents + " = " + xml;
            calc_screen.setText(contents);
        }
        catch(IOException e) { System.err.println(e); }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton back_button;
    private javax.swing.JTextField calc_screen;
    private javax.swing.JButton clear_button;
    private javax.swing.JButton div_button;
    private javax.swing.JButton eight_button;
    private javax.swing.JButton equals_button;
    private javax.swing.JButton five_button;
    private javax.swing.JButton four_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mult_button;
    private javax.swing.JButton nine_button;
    private javax.swing.JButton one_button;
    private javax.swing.JButton seven_button;
    private javax.swing.JButton six_button;
    private javax.swing.JButton sub_button;
    private javax.swing.JButton three_button;
    private javax.swing.JButton two_button;
    private javax.swing.JButton zero_button;
    // End of variables declaration//GEN-END:variables
}
